backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - label: "Announcements"
    name: "announcements"
    folder: "content/announcements"
    create: true
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
